extend dctl helper script

diff --git a/dctl b/dctl
--- a/dctl
+++ b/dctl
@@ -4,15 +4,15 @@
 #
 # @copyright (c) 2016 Patrick Paechnatz <patrick.paechnatz@gmail.com>
 # @author patrick.paechnatz@gmail.com
-# @updated 2016/21/07
-# @version 1.0.0
+# @updated 2016/29/07
+# @version 1.0.1
 #
 
 # activate strict mode for bash
 set -e
 
 # some default definitions
-VERSION="1.0.0"
+VERSION="1.0.1"
 
 # some default configuration constants
 SCRIPT_PATH=$(dirname "$0")
@@ -24,9 +24,63 @@ _show_title() {
 
 _show_short_help() {
     echo -e "$./dctl bai | --build-all-images             -> build all images inside this workbench"
+    echo -e "$./dctl val | --validate-workbench           -> validate all images availability for this workbench"
     echo -e "$./dctl rec | --remove-exited-container      -> remove all exited containers including 'ofs-volumes'"
     echo -e "$./dctl rac | --remove-all-container         -> remove all (!) containers including 'ofs-volumes'"
     echo -e "$./dctl rdi | --remove-dangling-images       -> remove all dangling <none>|<incomplete> images"
+}
+
+_image_build() {
+
+    img_name=""
+    img_path=""
+
+    while [[ ${1} ]]; do
+
+        case "${1}" in
+            img|--image-name)
+                img_name="${2}"
+                shift
+                ;;
+
+            path|--image-path)
+                img_path="${2}"
+                shift
+                ;;
+
+        esac
+        if ! shift; then
+            echo "missing parameter arguments!" >&2
+            return 1
+        fi
+    done
+
+   cd ${img_path} && docker build -t ${img_name} . && cd ..
+    _image_build_check img ${img_name}
+}
+
+_image_build_check() {
+
+    img_name=""
+    img_cnt=""
+
+    case "${1}" in
+        img|--image-name)
+
+            img_name="${2}"
+            img_cnt=$(docker images | grep "^$img_name" | wc -l)
+            if [ $img_cnt -eq 0 ]; then
+                echo -e "\n\033[0;31m[FAILURE] previously generated image ${img_name} not found!\033[0m <EXIT>\n"
+                _docker_image_clear
+                exit 9
+            else
+                echo -e "\033[1;92m[SUCCESS] image available -> ${img_name}\033[0m";
+            fi
+
+            shift
+        ;;
+
+    esac
 }
 
 _get_parameters() {
@@ -45,18 +99,19 @@ _get_parameters() {
                 exit 9
             fi
 
-            cd df-wb-centos-7; ./build; cd ..
-            cd df-wb-rdbs-mysql56; ./build; cd ..
-            cd df-wb-rdbs-mysql57; ./build; cd ..
-            cd df-wb-rdbs-postgresql93; ./build; cd ..
-            cd df-wb-rdbs-postgresql95; ./build; cd ..
-            cd df-wb-httpd-apache; ./build; cd ..
-            cd df-wb-httpd-apache-php56; ./build; cd ..
-            cd df-wb-httpd-apache-php70; ./build; cd ..
-            cd df-wb-app; ./build; cd ..
+            _image_build --image-name "local/df/wb/centos/7" --image-path "./df-wb-centos-7"
+            _image_build --image-name "local/df/wb/centos/7/rdbs/mysql56" --image-path "./df-wb-rdbs-mysql56"
+            _image_build --image-name "local/df/wb/centos/7/rdbs/mysql57" --image-path "./df-wb-rdbs-mysql57"
+            _image_build --image-name "local/df/wb/centos/7/rdbs/postresql93" --image-path "./df-wb-rdbs-postgresql93"
+            _image_build --image-name "local/df/wb/centos/7/rdbs/postresql95" --image-path "./df-wb-rdbs-postgresql95"
+            _image_build --image-name "local/df/wb/centos/7/httpd/apache" --image-path "./df-wb-httpd-apache"
+            _image_build --image-name "local/df/wb/centos/7/httpd/apache/php56" --image-path "./df-wb-httpd-apache-php56"
+            _image_build --image-name "local/df/wb/centos/7/httpd/apache/php70" --image-path "./df-wb-httpd-apache-php70"
+            _image_build --image-name "local/df/wb/centos/7/httpd/apache/php70/app" --image-path "./df-wb-app"
 
             shift
             ;;
+
         rec|--remove-exited-container)
             echo; read -p "remove all exited containers | are you sure (y/n/J/j) ?" -n 1 -r; echo
             if [[ ! $REPLY =~ ^[YyJj]$ ]]
@@ -67,6 +122,7 @@ _get_parameters() {
 
             shift
             ;;
+
         rac|--remove-all-container)
             echo; read -p "remove all (!) containers | are you sure (y/n/J/j) ?" -n 1 -r; echo
             if [[ ! $REPLY =~ ^[YyJj]$ ]]
@@ -77,6 +133,7 @@ _get_parameters() {
 
             shift
             ;;
+
         rdi|--remove-dangling-images)
             echo; read -p "remove all dangling images | are you sure (y/n/J/j) ?" -n 1 -r; echo
             if [[ ! $REPLY =~ ^[YyJj]$ ]]
@@ -85,6 +142,22 @@ _get_parameters() {
             fi
 
             docker images -q --filter "dangling=true" | xargs docker rmi -f
+            shift
+            ;;
+
+        val|--validate-workbench)
+            echo -e "validate all images of this workbench ...\n"
+
+            _image_build_check --image-name "local/df/wb/centos/7" --image-path "./df-wb-centos-7"
+            _image_build_check --image-name "local/df/wb/centos/7/rdbs/mysql56" --image-path "./df-wb-rdbs-mysql56"
+            _image_build_check --image-name "local/df/wb/centos/7/rdbs/mysql57" --image-path "./df-wb-rdbs-mysql57"
+            _image_build_check --image-name "local/df/wb/centos/7/rdbs/postresql93" --image-path "./df-wb-rdbs-postgresql93"
+            _image_build_check --image-name "local/df/wb/centos/7/rdbs/postresql95" --image-path "./df-wb-rdbs-postgresql95"
+            _image_build_check --image-name "local/df/wb/centos/7/httpd/apache" --image-path "./df-wb-httpd-apache"
+            _image_build_check --image-name "local/df/wb/centos/7/httpd/apache/php56" --image-path "./df-wb-httpd-apache-php56"
+            _image_build_check --image-name "local/df/wb/centos/7/httpd/apache/php70" --image-path "./df-wb-httpd-apache-php70"
+            _image_build_check --image-name "local/df/wb/centos/7/httpd/apache/php70/app" --image-path "./df-wb-app"
+
             shift
             ;;
 
